# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .available_operation_display_py3 import AvailableOperationDisplay
    from .available_operation_display_property_service_specification_metrics_item_py3 import AvailableOperationDisplayPropertyServiceSpecificationMetricsItem
    from .available_operation_display_property_service_specification_metrics_list_py3 import AvailableOperationDisplayPropertyServiceSpecificationMetricsList
    from .available_operation_py3 import AvailableOperation
    from .csrp_error_body_py3 import CSRPErrorBody
    from .csrp_error_py3 import CSRPError, CSRPErrorException
    from .customization_host_name_py3 import CustomizationHostName
    from .customization_ip_address_py3 import CustomizationIPAddress
    from .customization_ip_settings_py3 import CustomizationIPSettings
    from .customization_identity_user_data_py3 import CustomizationIdentityUserData
    from .customization_identity_py3 import CustomizationIdentity
    from .customization_nic_setting_py3 import CustomizationNicSetting
    from .customization_specification_py3 import CustomizationSpecification
    from .customization_policy_py3 import CustomizationPolicy
    from .sku_py3 import Sku
    from .dedicated_cloud_node_py3 import DedicatedCloudNode
    from .dedicated_cloud_service_py3 import DedicatedCloudService
    from .guest_os_customization_py3 import GuestOSCustomization
    from .guest_osnic_customization_py3 import GuestOSNICCustomization
    from .operation_error_py3 import OperationError
    from .operation_resource_py3 import OperationResource
    from .patch_payload_py3 import PatchPayload
    from .resource_pool_py3 import ResourcePool
    from .virtual_disk_controller_py3 import VirtualDiskController
    from .virtual_disk_py3 import VirtualDisk
    from .virtual_network_py3 import VirtualNetwork
    from .virtual_nic_py3 import VirtualNic
    from .virtual_machine_template_py3 import VirtualMachineTemplate
    from .private_cloud_py3 import PrivateCloud
    from .sku_availability_py3 import SkuAvailability
    from .usage_name_py3 import UsageName
    from .usage_py3 import Usage
    from .virtual_machine_py3 import VirtualMachine
    from .virtual_machine_stop_mode_py3 import VirtualMachineStopMode
except (SyntaxError, ImportError):
    from .available_operation_display import AvailableOperationDisplay
    from .available_operation_display_property_service_specification_metrics_item import AvailableOperationDisplayPropertyServiceSpecificationMetricsItem
    from .available_operation_display_property_service_specification_metrics_list import AvailableOperationDisplayPropertyServiceSpecificationMetricsList
    from .available_operation import AvailableOperation
    from .csrp_error_body import CSRPErrorBody
    from .csrp_error import CSRPError, CSRPErrorException
    from .customization_host_name import CustomizationHostName
    from .customization_ip_address import CustomizationIPAddress
    from .customization_ip_settings import CustomizationIPSettings
    from .customization_identity_user_data import CustomizationIdentityUserData
    from .customization_identity import CustomizationIdentity
    from .customization_nic_setting import CustomizationNicSetting
    from .customization_specification import CustomizationSpecification
    from .customization_policy import CustomizationPolicy
    from .sku import Sku
    from .dedicated_cloud_node import DedicatedCloudNode
    from .dedicated_cloud_service import DedicatedCloudService
    from .guest_os_customization import GuestOSCustomization
    from .guest_osnic_customization import GuestOSNICCustomization
    from .operation_error import OperationError
    from .operation_resource import OperationResource
    from .patch_payload import PatchPayload
    from .resource_pool import ResourcePool
    from .virtual_disk_controller import VirtualDiskController
    from .virtual_disk import VirtualDisk
    from .virtual_network import VirtualNetwork
    from .virtual_nic import VirtualNic
    from .virtual_machine_template import VirtualMachineTemplate
    from .private_cloud import PrivateCloud
    from .sku_availability import SkuAvailability
    from .usage_name import UsageName
    from .usage import Usage
    from .virtual_machine import VirtualMachine
    from .virtual_machine_stop_mode import VirtualMachineStopMode
from .available_operation_paged import AvailableOperationPaged
from .dedicated_cloud_node_paged import DedicatedCloudNodePaged
from .dedicated_cloud_service_paged import DedicatedCloudServicePaged
from .sku_availability_paged import SkuAvailabilityPaged
from .private_cloud_paged import PrivateCloudPaged
from .customization_policy_paged import CustomizationPolicyPaged
from .resource_pool_paged import ResourcePoolPaged
from .virtual_machine_template_paged import VirtualMachineTemplatePaged
from .virtual_network_paged import VirtualNetworkPaged
from .usage_paged import UsagePaged
from .virtual_machine_paged import VirtualMachinePaged
from .vmware_cloud_simple_client_enums import (
    OperationOrigin,
    AggregationType,
    NodeStatus,
    OnboardingStatus,
    DiskIndependenceMode,
    NICType,
    PrivateCloudResourceType,
    UsageCount,
    GuestOSType,
    VirtualMachineStatus,
    StopMode,
)

__all__ = [
    'AvailableOperationDisplay',
    'AvailableOperationDisplayPropertyServiceSpecificationMetricsItem',
    'AvailableOperationDisplayPropertyServiceSpecificationMetricsList',
    'AvailableOperation',
    'CSRPErrorBody',
    'CSRPError', 'CSRPErrorException',
    'CustomizationHostName',
    'CustomizationIPAddress',
    'CustomizationIPSettings',
    'CustomizationIdentityUserData',
    'CustomizationIdentity',
    'CustomizationNicSetting',
    'CustomizationSpecification',
    'CustomizationPolicy',
    'Sku',
    'DedicatedCloudNode',
    'DedicatedCloudService',
    'GuestOSCustomization',
    'GuestOSNICCustomization',
    'OperationError',
    'OperationResource',
    'PatchPayload',
    'ResourcePool',
    'VirtualDiskController',
    'VirtualDisk',
    'VirtualNetwork',
    'VirtualNic',
    'VirtualMachineTemplate',
    'PrivateCloud',
    'SkuAvailability',
    'UsageName',
    'Usage',
    'VirtualMachine',
    'VirtualMachineStopMode',
    'AvailableOperationPaged',
    'DedicatedCloudNodePaged',
    'DedicatedCloudServicePaged',
    'SkuAvailabilityPaged',
    'PrivateCloudPaged',
    'CustomizationPolicyPaged',
    'ResourcePoolPaged',
    'VirtualMachineTemplatePaged',
    'VirtualNetworkPaged',
    'UsagePaged',
    'VirtualMachinePaged',
    'OperationOrigin',
    'AggregationType',
    'NodeStatus',
    'OnboardingStatus',
    'DiskIndependenceMode',
    'NICType',
    'PrivateCloudResourceType',
    'UsageCount',
    'GuestOSType',
    'VirtualMachineStatus',
    'StopMode',
]
