# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationSpecification(Model):
    """The specification for Customization Policy.

    :param identity: Customization Identity. It contains data about user and
     hostname
    :type identity: ~azure.mgmt.vmwarecloudsimple.models.CustomizationIdentity
    :param nic_settings: Network interface settings
    :type nic_settings:
     list[~azure.mgmt.vmwarecloudsimple.models.CustomizationNicSetting]
    """

    _attribute_map = {
        'identity': {'key': 'identity', 'type': 'CustomizationIdentity'},
        'nic_settings': {'key': 'nicSettings', 'type': '[CustomizationNicSetting]'},
    }

    def __init__(self, *, identity=None, nic_settings=None, **kwargs) -> None:
        super(CustomizationSpecification, self).__init__(**kwargs)
        self.identity = identity
        self.nic_settings = nic_settings
