# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationIdentityUserData(Model):
    """Windows Identity. User data customization.

    :param is_password_predefined: Is password predefined in customization
     policy. Default value: False .
    :type is_password_predefined: bool
    """

    _attribute_map = {
        'is_password_predefined': {'key': 'isPasswordPredefined', 'type': 'bool'},
    }

    def __init__(self, *, is_password_predefined: bool=False, **kwargs) -> None:
        super(CustomizationIdentityUserData, self).__init__(**kwargs)
        self.is_password_predefined = is_password_predefined
