# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationIdentity(Model):
    """CustomizationIdentity.

    :param data: Windows Text Identity. Prepared data
    :type data: str
    :param host_name: Virtual machine host name settings
    :type host_name:
     ~azure.mgmt.vmwarecloudsimple.models.CustomizationHostName
    :param type: Identity type. Possible values include: 'WINDOWS_TEXT',
     'WINDOWS', 'LINUX'
    :type type: str or ~azure.mgmt.vmwarecloudsimple.models.enum
    :param user_data: Windows Identity. User data customization
    :type user_data:
     ~azure.mgmt.vmwarecloudsimple.models.CustomizationIdentityUserData
    """

    _attribute_map = {
        'data': {'key': 'data', 'type': 'str'},
        'host_name': {'key': 'hostName', 'type': 'CustomizationHostName'},
        'type': {'key': 'type', 'type': 'str'},
        'user_data': {'key': 'userData', 'type': 'CustomizationIdentityUserData'},
    }

    def __init__(self, **kwargs):
        super(CustomizationIdentity, self).__init__(**kwargs)
        self.data = kwargs.get('data', None)
        self.host_name = kwargs.get('host_name', None)
        self.type = kwargs.get('type', None)
        self.user_data = kwargs.get('user_data', None)
