# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationPolicy(Model):
    """The virtual machine customization policy.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param id: Customization policy azure id
    :type id: str
    :param location: Azure region
    :type location: str
    :ivar name: Customization policy name
    :vartype name: str
    :param description: Policy description
    :type description: str
    :param private_cloud_id: The Private cloud id
    :type private_cloud_id: str
    :param specification: Detailed customization policy specification
    :type specification:
     ~azure.mgmt.vmwarecloudsimple.models.CustomizationSpecification
    :param customization_policy_properties_type: The type of customization
     (Linux or Windows). Possible values include: 'LINUX', 'WINDOWS'
    :type customization_policy_properties_type: str or
     ~azure.mgmt.vmwarecloudsimple.models.enum
    :param version: Policy version
    :type version: str
    :ivar type:
    :vartype type: str
    """

    _validation = {
        'name': {'readonly': True},
        'type': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'description': {'key': 'properties.description', 'type': 'str'},
        'private_cloud_id': {'key': 'properties.privateCloudId', 'type': 'str'},
        'specification': {'key': 'properties.specification', 'type': 'CustomizationSpecification'},
        'customization_policy_properties_type': {'key': 'properties.type', 'type': 'str'},
        'version': {'key': 'properties.version', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(CustomizationPolicy, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.location = kwargs.get('location', None)
        self.name = None
        self.description = kwargs.get('description', None)
        self.private_cloud_id = kwargs.get('private_cloud_id', None)
        self.specification = kwargs.get('specification', None)
        self.customization_policy_properties_type = kwargs.get('customization_policy_properties_type', None)
        self.version = kwargs.get('version', None)
        self.type = None
