# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationIPSettings(Model):
    """CustomizationIPSettings.

    :param gateway: The list of gateways
    :type gateway: list[str]
    :param ip: Ip address customization settings
    :type ip: ~azure.mgmt.vmwarecloudsimple.models.CustomizationIPAddress
    :param subnet_mask: Adapter subnet mask
    :type subnet_mask: str
    """

    _attribute_map = {
        'gateway': {'key': 'gateway', 'type': '[str]'},
        'ip': {'key': 'ip', 'type': 'CustomizationIPAddress'},
        'subnet_mask': {'key': 'subnetMask', 'type': 'str'},
    }

    def __init__(self, *, gateway=None, ip=None, subnet_mask: str=None, **kwargs) -> None:
        super(CustomizationIPSettings, self).__init__(**kwargs)
        self.gateway = gateway
        self.ip = ip
        self.subnet_mask = subnet_mask
