# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationNicSetting(Model):
    """CustomizationNicSetting.

    :param adapter: The list of adapters' settings
    :type adapter:
     ~azure.mgmt.vmwarecloudsimple.models.CustomizationIPSettings
    :param mac_address: NIC mac address
    :type mac_address: str
    """

    _attribute_map = {
        'adapter': {'key': 'adapter', 'type': 'CustomizationIPSettings'},
        'mac_address': {'key': 'macAddress', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(CustomizationNicSetting, self).__init__(**kwargs)
        self.adapter = kwargs.get('adapter', None)
        self.mac_address = kwargs.get('mac_address', None)
