# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CustomizationIPAddress(Model):
    """CustomizationIPAddress.

    :param argument: Argument when Custom ip type is selected
    :type argument: str
    :param ip_address: Defined Ip Address when Fixed ip type is selected
    :type ip_address: str
    :param type: Customization Specification ip type. Possible values include:
     'CUSTOM', 'DHCP_IP', 'FIXED_IP', 'USER_DEFINED'
    :type type: str or ~azure.mgmt.vmwarecloudsimple.models.enum
    """

    _attribute_map = {
        'argument': {'key': 'argument', 'type': 'str'},
        'ip_address': {'key': 'ipAddress', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(CustomizationIPAddress, self).__init__(**kwargs)
        self.argument = kwargs.get('argument', None)
        self.ip_address = kwargs.get('ip_address', None)
        self.type = kwargs.get('type', None)
