# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GuestOSCustomization(Model):
    """Guest OS Customization properties.

    :param dns_servers: List of dns servers to use
    :type dns_servers: list[str]
    :param host_name: Virtual Machine hostname
    :type host_name: str
    :param password: Password for login
    :type password: str
    :param policy_id: id of customization policy
    :type policy_id: str
    :param username: Username for login
    :type username: str
    """

    _attribute_map = {
        'dns_servers': {'key': 'dnsServers', 'type': '[str]'},
        'host_name': {'key': 'hostName', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'policy_id': {'key': 'policyId', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(GuestOSCustomization, self).__init__(**kwargs)
        self.dns_servers = kwargs.get('dns_servers', None)
        self.host_name = kwargs.get('host_name', None)
        self.password = kwargs.get('password', None)
        self.policy_id = kwargs.get('policy_id', None)
        self.username = kwargs.get('username', None)
