# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .operations import Operations
from .dedicated_cloud_nodes_operations import DedicatedCloudNodesOperations
from .dedicated_cloud_services_operations import DedicatedCloudServicesOperations
from .skus_availability_operations import SkusAvailabilityOperations
from .private_clouds_operations import PrivateCloudsOperations
from .customization_policies_operations import CustomizationPoliciesOperations
from .resource_pools_operations import ResourcePoolsOperations
from .virtual_machine_templates_operations import VirtualMachineTemplatesOperations
from .virtual_networks_operations import VirtualNetworksOperations
from .usages_operations import UsagesOperations
from .virtual_machines_operations import VirtualMachinesOperations

__all__ = [
    'Operations',
    'DedicatedCloudNodesOperations',
    'DedicatedCloudServicesOperations',
    'SkusAvailabilityOperations',
    'PrivateCloudsOperations',
    'CustomizationPoliciesOperations',
    'ResourcePoolsOperations',
    'VirtualMachineTemplatesOperations',
    'VirtualNetworksOperations',
    'UsagesOperations',
    'VirtualMachinesOperations',
]
